version: '3.7'

services:
    influxdb:
        image: mendhak/arm32v6-influxdb
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - ./influxdbdata:/root/.influxdb/data/
            - ./influxdbbackups:/backups/

    chronograf:
        image: mendhak/arm32v6-chronograf
        container_name: chronograf
        ports:
            - 80:8888
        command: chronograf --influxdb-url=http://influxdb:8086 --bolt-path /chronografdata/bolt.db
        volumes:
            - ./chronografdata:/chronografdata/